jqassistant:
  plugins:
    - group-id: org.jqassistant.tooling.dashboard
      artifact-id: jqassistant-dashboard-plugin
      version: 1.0.0-SNAPSHOT
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-codecharta-plugin
      version: 1.0.0-M2
  scan:
    include:
      files:
        - .git
    properties:
      xml.file.include: "**/*.xml"
  analyze:
    concepts:
      - jqassistant-dashboard:ComponentVersionReport
      - jqassistant-dashboard-git:ComponentContributorsReport
    execute-applied-concepts: true
    report:
      properties:
        dashboard:
          url: http://localhost:8080/
          api-key: secret_api_token
          owner: "jqassistant"
          project: "plugins"
