= jQAssistant JEE Plugin

This is the JEE Plugin of https://jqassistant.org[jQAssistant^].

It provides concepts, constraints, and scanners for the following aspects:

* CDI, e.g.
** producer
** injection points
** interceptors
** decorators
** scopes
** event producer
** event consumer
* EJB 3, e.g.
** remote beans
** local beans
** stateful session beans
** singleton beans
** message driven beans
** scheduled methods
* Java EE 6, e.g.
** Web Application Archives
** Enterprise ARchive
* JPA 2, e.g.
** entities
** persistence units
** named queries

== Available Constraints

|===
|Technology |Constraint |Description

|CDI
|cdi:BeansMustUseConstructorInjection
|All CDI beans must use constructor injection.

|CDI
|cdi:BeansMustNotUseFieldInjection
|CDI beans shall not use field injection (constructor and setter injections are fine.).

|EJB 3
|ejb3:ScheduleMethodInEjbContext
|Check that Schedule methods are only declared in EJB classes.

|JPA 2
|jpa2:ValidationModeMustBeExplicitlySpecified
|The validation mode of all persistence units must be explicitly specified and either set to CALLBACK or NONE.
|===

== Using the jqassistant-jee-plugin

NOTE:: This plug-in supersedes the previously separated plugins for CDI, EJB3, JPA2, and JEE6.

NOTE:: From jQAssistant v2.0.0 onwards, it is not part of the core distribution anymore and a manual configuration as shown below is required.

[source, xml]
----
<plugin>
    <groupId>com.buschmais.jqassistant</groupId>
    <artifactId>jqassistant-maven-plugin</artifactId>
    <version>${jqassistant.version}</version>
    <executions>
        <execution>
            <id>default-cli</id>
            <goals>
                <goal>scan</goal>
                <goal>analyze</goal>
            </goals>
        </execution>
    </executions>
    <dependencies>
        <dependency> // <1>
            <groupId>org.jqassistant.plugin</groupId>
            <artifactId>jqassistant-jee-plugin</artifactId>
            <version>${jqassistant.jee-plugin.version}</version>
        </dependency>
    </dependencies>
</plugin>
----
<1> Dependency to the JEE plugin
